theme: jekyll-theme-minimal
title: Paludenera
description: "Un supplemento di ambientazione compatibile con La Scatola Bianca"

plugins:
  - "jekyll-github-metadata"
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge